export const deeplAPI =  "https://api-free.deepl.com/"
export const key = "5652c0b9-adcf-7f2e-f6a2-3a577f700dc9:fx"
export const targ_languages = {
                                "BG":"Bulgarian",
                                "CS":"Czech",
                                "DA":"Danish",
                                "DE":"German",
                                "EL":"Greek",
                                "EN-GB":"English (British)",
                                "EN-US":"English (American)",
                                "ES":"Spanish",
                                "ET":"Estonian",
                                "FI":"Finnish",
                                "FR":"French",
                                "HU":"Hungarian",
                                "IT":"Italian",
                                "JA":"Japanese",
                                "LT":"Lithuanian",
                                "LV":"Latvian",
                                "NL":"Dutch",
                                "PL":"Polish",
                                "PT-PT":"Portuguese",
                                "PT-BR":"Portuguese (Brazilian)",
                                "RO":"Romanian",
                                "RU":"Russian",
                                "SK":"Slovak",
                                "SL":"Slovenian",
                                "SV":"Swedish",
                                "ZH":"Chinese"}
