export const deeplAPI =  process.env.deeplAPI
export const key = process.env.deeplAPI_key
export const targ_languages = {
                                "BG":"Bulgarian",
                                "CS":"Czech",
                                "DA":"Danish",
                                "DE":"German",
                                "EL":"Greek",
                                "EN-GB":"English (British)",
                                "EN-US":"English (American)",
                                "ES":"Spanish",
                                "ET":"Estonian",
                                "FI":"Finnish",
                                "FR":"French",
                                "HU":"Hungarian",
                                "IT":"Italian",
                                "JA":"Japanese",
                                "LT":"Lithuanian",
                                "LV":"Latvian",
                                "NL":"Dutch",
                                "PL":"Polish",
                                "PT-PT":"Portuguese",
                                "PT-BR":"Portuguese (Brazilian)",
                                "RO":"Romanian",
                                "RU":"Russian",
                                "SK":"Slovak",
                                "SL":"Slovenian",
                                "SV":"Swedish",
                                "ZH":"Chinese"}
